Tracking Pull Request for Master (#312)
* Merge pull request #304 from clancychilds/feature-uk-jlp-card

add unittest for John Lewis Card importer

* [AT Raiffeisen 2019] Added missing date format

Also switched Payee to Memo until payee ID's have been properly implemented (otherwise there will be lots of duplicate payees)

* getting ready to build a nicer website for the project

* Added line for installing requirements.txt

Fixes #310

* Update to use preferred _preprocess_file method

* Little explanation

* Introduction of Github Actions (#308)

* Create Pull Request Labelling Github Workflow

* Add 'bank format' label to any change in bank conf

* Create Github action file equivalent to Travis (mostly)

* Remove MacOS and Windows temporarily

##[error]Version 3.4 with arch x64 not found
##[error]Node run failed with exit code 1

* Remove Python 3.4 from testing

Version 3.4 with arch x64 not found

* Temporarily disable code coverage check

Error: Missing repository upload token

* Remove Python nightly

Not supported

* Remove line length increase

We're not barbarians

* Add other operating systems back

* Kill Travis

Goodnight, sweet prince (fixes #309)

* Auto label changes to workflow folder (very meta)

* Clean up .gitignore

* Create codestyle workflow

* Deliberate whitespace error to test codestyle workflow

* Remove flake8 from testing.yml because of separate codestyle workflow

* Enable lint-action workflow using flake8 and black

* Fix code style issues with Black

* Fix code style issues with Black

* Remove unneeded CrossversionCsvReader import from plugin template

* Temporarily disable flake8 until we can configure line-length in black

* Add versioning.yml to fix #238 and #180

* Allow testing.yml to apply to pull requests to any branch

* Remove codeclimate.yml for now

* Add auto-release generation for any `master` commit

* Whitespace

Co-authored-by: Lint Action <lint-action@samuelmeuli.com>

* Fix code style issues with Black

Co-authored-by: Clancy Childs <clancychilds@users.noreply.github.com>
Co-authored-by: Torben Gundtofte-Bruun <torbengb@users.noreply.github.com>
Co-authored-by: Lint Action <lint-action@samuelmeuli.com>